# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d79b6da8a8902d8f0f20c20dc7cf278958abefd3e9ad3eaec464af14ea0fd6db9806d698b29414d72436062d677970f5bf7686049f6314fbb7ce75b6fff7f67

test:
  secret_key_base: dc0f0e22874305b340c4e81570f6592cf4140562ee756bf73d2b7c8a8401b52862ecdc81de0e507d378ad5a74736cba3abd7b4fd51dfce2f3faf941b33f39987

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
